const fs = require('fs');
const path = require('path');
const { HISTORICAL_DATA } = require('../data/historicalAugmentation');

// Players known to be missing due to scraper gaps (Defunct teams) or mysterious bugs
const MISSING_PLAYERS = {
    // Deccan Chargers
    "Adam Gilchrist": { role: "WK", overseas: true },
    "Herschelle Gibbs": { role: "BAT", overseas: true },
    "Andrew Symonds": { role: "AR", overseas: true },
    "Scott Styris": { role: "AR", overseas: true },
    "Shahid Afridi": { role: "AR", overseas: true },
    "Chaminda Vaas": { role: "BOWL", overseas: true },
    "RP Singh": { role: "BOWL", overseas: false },
    "Pragyan Ojha": { role: "BOWL", overseas: false },
    "VVS Laxman": { role: "BAT", overseas: false },
    "Rohit Sharma": { role: "BAT", overseas: false },

    // Delhi Daredevils
    "Virender Sehwag": { role: "BAT", overseas: false },
    "Gautam Gambhir": { role: "BAT", overseas: false },
    "Glenn McGrath": { role: "BOWL", overseas: true },
    "Shoaib Malik": { role: "AR", overseas: true },
    "Mohammad Asif": { role: "BOWL", overseas: true },
    "Dinesh Karthik": { role: "WK", overseas: false },
    "Tillakaratne Dilshan": { role: "AR", overseas: true },
    "Farveez Maharoof": { role: "AR", overseas: true },
    "Daniel Vettori": { role: "AR", overseas: true },
    "Amit Mishra": { role: "BOWL", overseas: false },

    // KKR
    "Shoaib Akhtar": { role: "BOWL", overseas: true },
    "Ricky Ponting": { role: "BAT", overseas: true },
    "Umar Gul": { role: "BOWL", overseas: true },
    "Salman Butt": { role: "BAT", overseas: true },
    "Mohammad Hafeez": { role: "AR", overseas: true },

    // RR
    "Sohail Tanvir": { role: "BOWL", overseas: true },
    "Shane Warne": { role: "BOWL", overseas: true },
    "Kamran Akmal": { role: "WK", overseas: true },
    "Younis Khan": { role: "BAT", overseas: true },

    // MI
    "Sanath Jayasuriya": { role: "AR", overseas: true },
    "Shaun Pollock": { role: "AR", overseas: true },
    "Ashish Nehra": { role: "BOWL", overseas: false },

    // KXIP
    "Brett Lee": { role: "BOWL", overseas: true },
    "Yuvraj Singh": { role: "AR", overseas: false },
    "Kumar Sangakkara": { role: "WK", overseas: true },
    "Mahela Jayawardene": { role: "BAT", overseas: true },
    "S Sreesanth": { role: "BOWL", overseas: false },
    "Irfan Pathan": { role: "AR", overseas: false },

    // CSK (Mystery Missing)
    "MS Dhoni": { role: "WK", overseas: false },
    "Matthew Hayden": { role: "BAT", overseas: true },
    "Michael Hussey": { role: "BAT", overseas: true },
    "Muttiah Muralitharan": { role: "BOWL", overseas: true },
    "Jacob Oram": { role: "AR", overseas: true },
    "Stephen Fleming": { role: "BAT", overseas: true },
    "Makhaya Ntini": { role: "BOWL", overseas: true },
    "Suresh Raina": { role: "BAT", overseas: false }
};

console.log("Original count:", Object.keys(HISTORICAL_DATA).length);

Object.entries(MISSING_PLAYERS).forEach(([name, data]) => {
    if (!HISTORICAL_DATA[name]) {
        console.log(`Restoring missing: ${name}`);
        HISTORICAL_DATA[name] = data;
    } else {
        // console.log(`Exists: ${name}`);
    }
});

console.log("New count:", Object.keys(HISTORICAL_DATA).length);

let fileContent = `
// Lookup table for historical players to fix missing Role and Overseas data
// Roles: BAT, BOWL, AR, WK
// Auto-generated by update_historical_data.js and restored by restore_manual_data.js
const HISTORICAL_DATA = {
`;

Object.keys(HISTORICAL_DATA).sort().forEach(name => {
    const p = HISTORICAL_DATA[name];
    fileContent += `    "${name}": { role: "${p.role}", overseas: ${p.overseas} },\n`;
});

fileContent += `};

const getAugmentedData = (playerName) => {
    if (!playerName) return null;
    
    // Direct match
    if (HISTORICAL_DATA[playerName]) {
        return HISTORICAL_DATA[playerName];
    }
    
    // Case-insensitive match
    const lowerName = playerName.toLowerCase();
    const key = Object.keys(HISTORICAL_DATA).find(k => k.toLowerCase() === lowerName);
    if (key) return HISTORICAL_DATA[key];

    return null;
};

module.exports = { getAugmentedData, HISTORICAL_DATA };
`;

fs.writeFileSync(path.join(__dirname, '../data/historicalAugmentation.js'), fileContent);
console.log("Restoration complete.");
