const fs = require('fs');
const path = require('path');

const MASTER_FILE = path.join(__dirname, '../data/iplt20_master_data.json');
const TARGET_FILE = path.join(__dirname, '../data/historicalAugmentation.js');

try {
    const masterData = JSON.parse(fs.readFileSync(MASTER_FILE, 'utf8'));
    const playerStats = {};

    console.log("Aggregating data from master file...");
    Object.values(masterData).forEach(yearData => {
        Object.entries(yearData).forEach(([key, p]) => {
            const name = key.trim();
            if (!playerStats[name]) {
                playerStats[name] = { roles: [], overseasCount: 0, totalCount: 0 };
            }
            playerStats[name].roles.push(p.role);
            if (p.overseas) playerStats[name].overseasCount++;
            playerStats[name].totalCount++;
        });
    });

    const finalData = {};
    console.log(`Found ${Object.keys(playerStats).length} unique players.`);

    Object.keys(playerStats).sort().forEach(name => {
        const stats = playerStats[name];

        // Most frequent role
        const roleCounts = {};
        stats.roles.forEach(r => roleCounts[r] = (roleCounts[r] || 0) + 1);
        const bestRole = Object.keys(roleCounts).reduce((a, b) => roleCounts[a] > roleCounts[b] ? a : b);

        // Majority vote for overseas
        const overseas = (stats.overseasCount / stats.totalCount) > 0.5;

        finalData[name] = { role: bestRole, overseas };
    });

    let fileContent = `
// Lookup table for historical players to fix missing Role and Overseas data
// Roles: BAT, BOWL, AR, WK
// Auto-generated by update_historical_data.js based on iplt20.com scrape
const HISTORICAL_DATA = {
`;

    Object.keys(finalData).forEach(name => {
        const p = finalData[name];
        fileContent += `    "${name}": { role: "${p.role}", overseas: ${p.overseas} },\n`;
    });

    fileContent += `};

const getAugmentedData = (playerName) => {
    if (!playerName) return null;
    
    // Direct match
    if (HISTORICAL_DATA[playerName]) {
        return HISTORICAL_DATA[playerName];
    }
    
    // Case-insensitive match
    const lowerName = playerName.toLowerCase();
    const key = Object.keys(HISTORICAL_DATA).find(k => k.toLowerCase() === lowerName);
    if (key) return HISTORICAL_DATA[key];

    // Partial match could be added here if needed
    
    return null;
};

module.exports = { getAugmentedData, HISTORICAL_DATA };
`;

    fs.writeFileSync(TARGET_FILE, fileContent);
    console.log("Successfully updated historicalAugmentation.js");

} catch (err) {
    console.error("Error updating data:", err);
    fs.writeFileSync('update_error.log', err.toString() + "\n" + err.stack);
    process.exit(1);
}
